<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        /*   $countries = [
            ['code' => 'AF', 'country_enName' => 'Afghan', 'country_arName' => 'أفغانستان', 'country_enNationality' => 'Afghanistan', 'country_arNationality' => 'أفغانستاني'],
            ['code' => 'AL', 'country_enName' => 'Albania', 'country_arName' => 'ألبانيا', 'country_enNationality' => 'Albanian', 'country_arNationality' => 'ألباني'],
            ['code' => 'AX', 'country_enName' => 'Aland Islands', 'country_arName' => 'جزر آلاند', 'country_enNationality' => 'Aland Islander', 'country_arNationality' => 'آلاندي'],
            ['code' => 'DZ', 'country_enName' => 'Algeria', 'country_arName' => 'الجزائر', 'country_enNationality' => 'Algerian', 'country_arNationality' => 'جزائري'],
            ['code' => 'AS', 'country_enName' => 'American Samoa', 'country_arName' => 'ساموا-الأمريكي', 'country_enNationality' => 'American Samoan', 'country_arNationality' => 'أمريكي سامواني'],
            ['code' => 'AD', 'country_enName' => 'Andorra', 'country_arName' => 'أندورا', 'country_enNationality' => 'Andorran', 'country_arNationality' => 'أندوري'],
            ['code' => 'AO', 'country_enName' => 'Angola', 'country_arName' => 'أنغولا', 'country_enNationality' => 'Angolan', 'country_arNationality' => 'أنقولي'],
            ['code' => 'AI', 'country_enName' => 'Anguilla', 'country_arName' => 'أنغويلا', 'country_enNationality' => 'Anguillan', 'country_arNationality' => 'أنغويلي'],
            ['code' => 'AQ', 'country_enName' => 'Antarctica', 'country_arName' => 'أنتاركتيكا', 'country_enNationality' => 'Antarctican', 'country_arNationality' => 'أنتاركتيكي'],
            ['code' => 'AG', 'country_enName' => 'Antigua and Barbuda', 'country_arName' => 'أنتيغوا وبربودا', 'country_enNationality' => 'Antiguan', 'country_arNationality' => 'بربودي'],
            ['code' => 'AR', 'country_enName' => 'Argentina', 'country_arName' => 'الأرجنتين', 'country_enNationality' => 'Argentinian', 'country_arNationality' => 'أرجنتيني'],
            ['code' => 'AM', 'country_enName' => 'Armenia', 'country_arName' => 'أرمينيا', 'country_enNationality' => 'Armenian', 'country_arNationality' => 'أرميني'],
            ['code' => 'AW', 'country_enName' => 'Aruba', 'country_arName' => 'أروبه', 'country_enNationality' => 'Aruban', 'country_arNationality' => 'أوروبهيني'],
            ['code' => 'AU', 'country_enName' => 'Australia', 'country_arName' => 'أستراليا', 'country_enNationality' => 'Australian', 'country_arNationality' => 'أسترالي'],
            ['code' => 'AT', 'country_enName' => 'Austria', 'country_arName' => 'النمسا', 'country_enNationality' => 'Austrian', 'country_arNationality' => 'نمساوي'],
            ['code' => 'AZ', 'country_enName' => 'Azerbaijan', 'country_arName' => 'أذربيجان', 'country_enNationality' => 'Azerbaijani', 'country_arNationality' => 'أذربيجاني'],
            ['code' => 'BS', 'country_enName' => 'Bahamas', 'country_arName' => 'الباهاماس', 'country_enNationality' => 'Bahamian', 'country_arNationality' => 'باهاميسي'],
            ['code' => 'BH', 'country_enName' => 'Bahrain', 'country_arName' => 'البحرين', 'country_enNationality' => 'Bahraini', 'country_arNationality' => 'بحريني'],
            ['code' => 'BD', 'country_enName' => 'Bangladesh', 'country_arName' => 'بنغلاديش', 'country_enNationality' => 'Bangladeshi', 'country_arNationality' => 'بنغلاديشي'],
            ['code' => 'BB', 'country_enName' => 'Barbados', 'country_arName' => 'بربادوس', 'country_enNationality' => 'Barbadian', 'country_arNationality' => 'بربادوسي'],
            ['code' => 'BY', 'country_enName' => 'Belarus', 'country_arName' => 'روسيا البيضاء', 'country_enNationality' => 'Belarusian', 'country_arNationality' => 'روسي'],
            ['code' => 'BE', 'country_enName' => 'Belgium', 'country_arName' => 'بلجيكا', 'country_enNationality' => 'Belgian', 'country_arNationality' => 'بلجيكي'],
            ['code' => 'BZ', 'country_enName' => 'Belize', 'country_arName' => 'بيليز', 'country_enNationality' => 'Belizean', 'country_arNationality' => 'بيليزي'],
            ['code' => 'BJ', 'country_enName' => 'Benin', 'country_arName' => 'بنين', 'country_enNationality' => 'Beninese', 'country_arNationality' => 'بنيني'],
            ['code' => 'BL', 'country_enName' => 'Saint Barthelemy', 'country_arName' => 'سان بارتيلمي', 'country_enNationality' => 'Saint Barthelmian', 'country_arNationality' => 'سان بارتيلمي'],
            ['code' => 'BM', 'country_enName' => 'Bermuda', 'country_arName' => 'جزر برمودا', 'country_enNationality' => 'Bermudan', 'country_arNationality' => 'برمودي'],
            ['code' => 'BT', 'country_enName' => 'Bhutan', 'country_arName' => 'بوتان', 'country_enNationality' => 'Bhutanese', 'country_arNationality' => 'بوتاني'],
            ['code' => 'BO', 'country_enName' => 'Bolivia', 'country_arName' => 'بوليفيا', 'country_enNationality' => 'Bolivian', 'country_arNationality' => 'بوليفي'],
            ['code' => 'BA', 'country_enName' => 'Bosnia and Herzegovina', 'country_arName' => 'البوسنة و الهرسك', 'country_enNationality' => 'Bosnian / Herzegovinian', 'country_arNationality' => 'بوسني/هرسكي'],
            ['code' => 'BW', 'country_enName' => 'Botswana', 'country_arName' => 'بوتسوانا', 'country_enNationality' => 'Botswanan', 'country_arNationality' => 'بوتسواني'],
            ['code' => 'BV', 'country_enName' => 'Bouvet Island', 'country_arName' => 'جزيرة بوفيه', 'country_enNationality' => 'Bouvetian', 'country_arNationality' => 'بوفيهي'],
            ['code' => 'BR', 'country_enName' => 'Brazil', 'country_arName' => 'البرازيل', 'country_enNationality' => 'Brazilian', 'country_arNationality' => 'برازيلي'],
            ['code' => 'IO', 'country_enName' => 'British Indian Ocean Territory', 'country_arName' => 'إقليم المحيط الهندي البريطاني', 'country_enNationality' => 'British Indian Ocean Territory', 'country_arNationality' => 'إقليم المحيط الهندي البريطاني'],
            ['code' => 'BN', 'country_enName' => 'Brunei Darussalam', 'country_arName' => 'بروني', 'country_enNationality' => 'Bruneian', 'country_arNationality' => 'بروني'],
            ['code' => 'BG', 'country_enName' => 'Bulgaria', 'country_arName' => 'بلغاريا', 'country_enNationality' => 'Bulgarian', 'country_arNationality' => 'بلغاري'],
            ['code' => 'BF', 'country_enName' => 'Burkina Faso', 'country_arName' => 'بوركينا فاسو', 'country_enNationality' => 'Burkinabe', 'country_arNationality' => 'بوركيني'],
            ['code' => 'BI', 'country_enName' => 'Burundi', 'country_arName' => 'بوروندي', 'country_enNationality' => 'Burundian', 'country_arNationality' => 'بورونيدي'],
            ['code' => 'KH', 'country_enName' => 'Cambodia', 'country_arName' => 'كمبوديا', 'country_enNationality' => 'Cambodian', 'country_arNationality' => 'كمبودي'],
            ['code' => 'CM', 'country_enName' => 'Cameroon', 'country_arName' => 'كاميرون', 'country_enNationality' => 'Cameroonian', 'country_arNationality' => 'كاميروني'],
            ['code' => 'CA', 'country_enName' => 'Canada', 'country_arName' => 'كندا', 'country_enNationality' => 'Canadian', 'country_arNationality' => 'كندي'],
            ['code' => 'CV', 'country_enName' => 'Cape Verde', 'country_arName' => 'الرأس الأخضر', 'country_enNationality' => 'Cape Verdean', 'country_arNationality' => 'الرأس الأخضر'],
            ['code' => 'KY', 'country_enName' => 'Cayman Islands', 'country_arName' => 'جزر كايمان', 'country_enNationality' => 'Caymanian', 'country_arNationality' => 'كايماني'],
            ['code' => 'CF', 'country_enName' => 'Central African Republic', 'country_arName' => 'جمهورية أفريقيا الوسطى', 'country_enNationality' => 'Central African', 'country_arNationality' => 'أفريقي'],
            ['code' => 'TD', 'country_enName' => 'Chad', 'country_arName' => 'تشاد', 'country_enNationality' => 'Chadian', 'country_arNationality' => 'تشادي'],
            ['code' => 'CL', 'country_enName' => 'Chile', 'country_arName' => 'شيلي', 'country_enNationality' => 'Chilean', 'country_arNationality' => 'شيلي'],
            ['code' => 'CN', 'country_enName' => 'China', 'country_arName' => 'الصين', 'country_enNationality' => 'Chinese', 'country_arNationality' => 'صيني'],
            ['code' => 'CX', 'country_enName' => 'Christmas Island', 'country_arName' => 'جزيرة عيد الميلاد', 'country_enNationality' => 'Christmas Islander', 'country_arNationality' => 'جزيرة عيد الميلاد'],
            ['code' => 'CC', 'country_enName' => 'Cocos (Keeling) Islands', 'country_arName' => 'جزر كوكوس', 'country_enNationality' => 'Cocos Islander', 'country_arNationality' => 'جزر كوكوس'],
            ['code' => 'CO', 'country_enName' => 'Colombia', 'country_arName' => 'كولومبيا', 'country_enNationality' => 'Colombian', 'country_arNationality' => 'كولومبي'],
            ['code' => 'KM', 'country_enName' => 'Comoros', 'country_arName' => 'جزر القمر', 'country_enNationality' => 'Comorian', 'country_arNationality' => 'جزر القمر'],
            ['code' => 'CG', 'country_enName' => 'Congo', 'country_arName' => 'الكونغو', 'country_enNationality' => 'Congolese', 'country_arNationality' => 'كونغي'],
            ['code' => 'CK', 'country_enName' => 'Cook Islands', 'country_arName' => 'جزر كوك', 'country_enNationality' => 'Cook Islander', 'country_arNationality' => 'جزر كوك'],
            ['code' => 'CR', 'country_enName' => 'Costa Rica', 'country_arName' => 'كوستاريكا', 'country_enNationality' => 'Costa Rican', 'country_arNationality' => 'كوستاريكي'],
            ['code' => 'HR', 'country_enName' => 'Croatia', 'country_arName' => 'كرواتيا', 'country_enNationality' => 'Croatian', 'country_arNationality' => 'كوراتي'],
            ['code' => 'CU', 'country_enName' => 'Cuba', 'country_arName' => 'كوبا', 'country_enNationality' => 'Cuban', 'country_arNationality' => 'كوبي'],
            ['code' => 'CY', 'country_enName' => 'Cyprus', 'country_arName' => 'قبرص', 'country_enNationality' => 'Cypriot', 'country_arNationality' => 'قبرصي'],
            ['code' => 'CW', 'country_enName' => 'Curaçao', 'country_arName' => 'كوراساو', 'country_enNationality' => 'Curacian', 'country_arNationality' => 'كوراساوي'],
            ['code' => 'CZ', 'country_enName' => 'Czech Republic', 'country_arName' => 'الجمهورية التشيكية', 'country_enNationality' => 'Czech', 'country_arNationality' => 'تشيكي'],
            ['code' => 'DK', 'country_enName' => 'Denmark', 'country_arName' => 'الدانمارك', 'country_enNationality' => 'Danish', 'country_arNationality' => 'دنماركي'],
            ['code' => 'DJ', 'country_enName' => 'Djibouti', 'country_arName' => 'جيبوتي', 'country_enNationality' => 'Djiboutian', 'country_arNationality' => 'جيبوتي'],
            ['code' => 'DM', 'country_enName' => 'Dominica', 'country_arName' => 'دومينيكا', 'country_enNationality' => 'Dominican', 'country_arNationality' => 'دومينيكي'],
            ['code' => 'DO', 'country_enName' => 'Dominican Republic', 'country_arName' => 'الجمهورية الدومينيكية', 'country_enNationality' => 'Dominican', 'country_arNationality' => 'دومينيكي'],
            ['code' => 'EC', 'country_enName' => 'Ecuador', 'country_arName' => 'إكوادور', 'country_enNationality' => 'Ecuadorian', 'country_arNationality' => 'إكوادوري'],
            ['code' => 'EG', 'country_enName' => 'Egypt', 'country_arName' => 'مصر', 'country_enNationality' => 'Egyptian', 'country_arNationality' => 'مصري'],
            ['code' => 'SV', 'country_enName' => 'El Salvador', 'country_arName' => 'إلسلفادور', 'country_enNationality' => 'Salvadoran', 'country_arNationality' => 'سلفادوري'],
            ['code' => 'GQ', 'country_enName' => 'Equatorial Guinea', 'country_arName' => 'غينيا الاستوائي', 'country_enNationality' => 'Equatorial Guinean', 'country_arNationality' => 'غيني'],
            ['code' => 'ER', 'country_enName' => 'Eritrea', 'country_arName' => 'إريتريا', 'country_enNationality' => 'Eritrean', 'country_arNationality' => 'إريتيري'],
            ['code' => 'EE', 'country_enName' => 'Estonia', 'country_arName' => 'استونيا', 'country_enNationality' => 'Estonian', 'country_arNationality' => 'استوني'],
            ['code' => 'ET', 'country_enName' => 'Ethiopia', 'country_arName' => 'أثيوبيا', 'country_enNationality' => 'Ethiopian', 'country_arNationality' => 'أثيوبي'],
            ['code' => 'FK', 'country_enName' => 'Falkland Islands (Malvinas)', 'country_arName' => 'جزر فوكلاند', 'country_enNationality' => 'Falkland Islander', 'country_arNationality' => 'فوكلاندي'],
            ['code' => 'FO', 'country_enName' => 'Faroe Islands', 'country_arName' => 'جزر فارو', 'country_enNationality' => 'Faroese', 'country_arNationality' => 'جزر فارو'],
            ['code' => 'FJ', 'country_enName' => 'Fiji', 'country_arName' => 'فيجي', 'country_enNationality' => 'Fijian', 'country_arNationality' => 'فيجي'],
            ['code' => 'FI', 'country_enName' => 'Finland', 'country_arName' => 'فنلندا', 'country_enNationality' => 'Finnish', 'country_arNationality' => 'فنلندي'],
            ['code' => 'FR', 'country_enName' => 'France', 'country_arName' => 'فرنسا', 'country_enNationality' => 'French', 'country_arNationality' => 'فرنسي'],
            ['code' => 'GF', 'country_enName' => 'French Guiana', 'country_arName' => 'غويانا الفرنسية', 'country_enNationality' => 'French Guianese', 'country_arNationality' => 'غويانا الفرنسية'],
            ['code' => 'PF', 'country_enName' => 'French Polynesia', 'country_arName' => 'بولينيزيا الفرنسية', 'country_enNationality' => 'French Polynesian', 'country_arNationality' => 'بولينيزيي'],
            ['code' => 'TF', 'country_enName' => 'French Southern and Antarctic Lands', 'country_arName' => 'أراض فرنسية جنوبية وأنتارتيكية', 'country_enNationality' => 'French', 'country_arNationality' => 'أراض فرنسية جنوبية وأنتارتيكية'],
            ['code' => 'GA', 'country_enName' => 'Gabon', 'country_arName' => 'الغابون', 'country_enNationality' => 'Gabonese', 'country_arNationality' => 'غابوني'],
            ['code' => 'GM', 'country_enName' => 'Gambia', 'country_arName' => 'غامبيا', 'country_enNationality' => 'Gambian', 'country_arNationality' => 'غامبي'],
            ['code' => 'GE', 'country_enName' => 'Georgia', 'country_arName' => 'جيورجيا', 'country_enNationality' => 'Georgian', 'country_arNationality' => 'جيورجي'],
            ['code' => 'DE', 'country_enName' => 'Germany', 'country_arName' => 'ألمانيا', 'country_enNationality' => 'German', 'country_arNationality' => 'ألماني'],
            ['code' => 'GH', 'country_enName' => 'Ghana', 'country_arName' => 'غانا', 'country_enNationality' => 'Ghanaian', 'country_arNationality' => 'غاني'],
            ['code' => 'GI', 'country_enName' => 'Gibraltar', 'country_arName' => 'جبل طارق', 'country_enNationality' => 'Gibraltar', 'country_arNationality' => 'جبل طارق'],
            ['code' => 'GG', 'country_enName' => 'Guernsey', 'country_arName' => 'غيرنزي', 'country_enNationality' => 'Guernsian', 'country_arNationality' => 'غيرنزي'],
            ['code' => 'GR', 'country_enName' => 'Greece', 'country_arName' => 'اليونان', 'country_enNationality' => 'Greek', 'country_arNationality' => 'يوناني'],
            ['code' => 'GL', 'country_enName' => 'Greenland', 'country_arName' => 'جرينلاند', 'country_enNationality' => 'Greenlandic', 'country_arNationality' => 'جرينلاندي'],
            ['code' => 'GD', 'country_enName' => 'Grenada', 'country_arName' => 'غرينادا', 'country_enNationality' => 'Grenadian', 'country_arNationality' => 'غرينادي'],
            ['code' => 'GP', 'country_enName' => 'Guadeloupe', 'country_arName' => 'جزر جوادلوب', 'country_enNationality' => 'Guadeloupe', 'country_arNationality' => 'جزر جوادلوب'],
            ['code' => 'GU', 'country_enName' => 'Guam', 'country_arName' => 'جوام', 'country_enNationality' => 'Guamanian', 'country_arNationality' => 'جوامي'],            ['code' => 'Afghanistan', 'country_enName' => 'AF', 'country_arName' => 'AF', 'country_enNationality' => 'AF', 'country_arNationality' => 'AF'],
            ['code' => 'GT', 'country_enName' => 'Guatemala', 'country_arName' => 'غواتيمال', 'country_enNationality' => 'Guatemalan', 'country_arNationality' => 'غواتيمالي'],
            ['code' => 'GN', 'country_enName' => 'Guinea', 'country_arName' => 'غينيا', 'country_enNationality' => 'Guinean', 'country_arNationality' => 'غيني'],
            ['code' => 'GW', 'country_enName' => 'Guinea-Bissau', 'country_arName' => 'غينيا-بيساو', 'country_enNationality' => 'Guinea-Bissauan', 'country_arNationality' => 'غيني'],
            ['code' => 'GY', 'country_enName' => 'Guyana', 'country_arName' => 'غيانا', 'country_enNationality' => 'Guyanese', 'country_arNationality' => 'غياني'],
            ['code' => 'HT', 'country_enName' => 'Haiti', 'country_arName' => 'هايتي', 'country_enNationality' => 'Haitian', 'country_arNationality' => 'هايتي'],
            ['code' => 'HM', 'country_enName' => 'Heard and Mc Donald Islands', 'country_arName' => 'جزيرة هيرد وجزر ماكدونالد', 'country_enNationality' => 'Heard and Mc Donald Islanders', 'country_arNationality' => 'جزيرة هيرد وجزر ماكدونالد'],
            ['code' => 'HN', 'country_enName' => 'Honduras', 'country_arName' => 'هندوراس', 'country_enNationality' => 'Honduran', 'country_arNationality' => 'هندوراسي'],
            ['code' => 'HK', 'country_enName' => 'Hong Kong', 'country_arName' => 'هونغ كونغ', 'country_enNationality' => 'Hongkongese', 'country_arNationality' => 'هونغ كونغي'],
            ['code' => 'HU', 'country_enName' => 'Hungary', 'country_arName' => 'المجر', 'country_enNationality' => 'Hungarian', 'country_arNationality' => 'مجري'],
            ['code' => 'IS', 'country_enName' => 'Iceland', 'country_arName' => 'آيسلندا', 'country_enNationality' => 'Icelandic', 'country_arNationality' => 'آيسلندي'],
            ['code' => 'IN', 'country_enName' => 'India', 'country_arName' => 'الهند', 'country_enNationality' => 'Indian', 'country_arNationality' => 'هندي'],
            ['code' => 'IM', 'country_enName' => 'Isle of Man', 'country_arName' => 'جزيرة مان', 'country_enNationality' => 'Manx', 'country_arNationality' => 'ماني'],
            ['code' => 'ID', 'country_enName' => 'Indonesia', 'country_arName' => 'أندونيسيا', 'country_enNationality' => 'Indonesian', 'country_arNationality' => 'أندونيسيي'],
            ['code' => 'IR', 'country_enName' => 'Iran', 'country_arName' => 'إيران', 'country_enNationality' => 'Iranian', 'country_arNationality' => 'إيراني'],
            ['code' => 'IQ', 'country_enName' => 'Iraq', 'country_arName' => 'العراق', 'country_enNationality' => 'Iraqi', 'country_arNationality' => 'Iraqi'],
            ['code' => 'IE', 'country_enName' => 'Ireland', 'country_arName' => 'إيرلندا', 'country_enNationality' => 'Irish', 'country_arNationality' => 'إيرلندي'],
            ['code' => 'IT', 'country_enName' => 'Italy', 'country_arName' => 'إيطاليا', 'country_enNationality' => 'Italian', 'country_arNationality' => 'إيطالي'],
            ['code' => 'CI', 'country_enName' => 'Ivory Coast', 'country_arName' => 'ساحل العاج', 'country_enNationality' => 'Ivory Coastian', 'country_arNationality' => 'ساحل العاج'],
            ['code' => 'JE', 'country_enName' => 'Jersey', 'country_arName' => 'جيرزي', 'country_enNationality' => 'Jersian', 'country_arNationality' => 'جيرزي'],
            ['code' => 'JM', 'country_enName' => 'Jamaica', 'country_arName' => 'جمايكا', 'country_enNationality' => 'Jamaican', 'country_arNationality' => 'جمايكي'],
            ['code' => 'JP', 'country_enName' => 'Japan', 'country_arName' => 'اليابان', 'country_enNationality' => 'Japanese', 'country_arNationality' => 'ياباني'],
            ['code' => 'JO', 'country_enName' => 'Jordan', 'country_arName' => 'الأردن', 'country_enNationality' => 'Jordanian', 'country_arNationality' => 'أردني'],
            ['code' => 'KZ', 'country_enName' => 'Kazakhstan', 'country_arName' => 'كازاخستان', 'country_enNationality' => 'Kazakh', 'country_arNationality' => 'كازاخستاني'],
            ['code' => 'KE', 'country_enName' => 'Kenya', 'country_arName' => 'كينيا', 'country_enNationality' => 'Kenyan', 'country_arNationality' => 'كيني'],
            ['code' => 'KI', 'country_enName' => 'Kiribati', 'country_arName' => 'كيريباتي', 'country_enNationality' => 'I-Kiribati', 'country_arNationality' => 'كيريباتي'],
            ['code' => 'KP', 'country_enName' => 'Korea(North Korea)', 'country_arName' => 'كوريا الشمالية', 'country_enNationality' => 'North Korean', 'country_arNationality' => 'كوري'],
            ['code' => 'KR', 'country_enName' => 'Korea(South Korea)', 'country_arName' => 'كوريا الجنوبية', 'country_enNationality' => 'South Korean', 'country_arNationality' => 'كوري'],
            ['code' => 'XK', 'country_enName' => 'Kosovo', 'country_arName' => 'كوسوفو', 'country_enNationality' => 'Kosovar', 'country_arNationality' => 'كوسيفي'],
            ['code' => 'KW', 'country_enName' => 'Kuwait', 'country_arName' => 'الكويت', 'country_enNationality' => 'Kuwaiti', 'country_arNationality' => 'كويتي'],
            ['code' => 'KG', 'country_enName' => 'Kyrgyzstan', 'country_arName' => 'قيرغيزستان', 'country_enNationality' => 'Kyrgyzstani', 'country_arNationality' => 'قيرغيزستاني'],
            ['code' => 'LA', 'country_enName' => 'Lao PDR', 'country_arName' => 'لاوس', 'country_enNationality' => 'Laotian', 'country_arNationality' => 'لاوسي'],
            ['code' => 'LV', 'country_enName' => 'Latvia', 'country_arName' => 'لاتفيا', 'country_enNationality' => 'Latvian', 'country_arNationality' => 'لاتيفي'],
            ['code' => 'LB', 'country_enName' => 'Lebanon', 'country_arName' => 'لبنان', 'country_enNationality' => 'Lebanese', 'country_arNationality' => 'لبناني'],
            ['code' => 'LS', 'country_enName' => 'Lesotho', 'country_arName' => 'ليسوتو', 'country_enNationality' => 'Basotho', 'country_arNationality' => 'ليوسيتي'],
            ['code' => 'LR', 'country_enName' => 'Liberia', 'country_arName' => 'ليبيريا', 'country_enNationality' => 'Liberian', 'country_arNationality' => 'ليبيري'],
            ['code' => 'LY', 'country_enName' => 'Libya', 'country_arName' => 'ليبيا', 'country_enNationality' => 'Libyan', 'country_arNationality' => 'ليبي'],
            ['code' => 'LI', 'country_enName' => 'Liechtenstein', 'country_arName' => 'ليختنشتين', 'country_enNationality' => 'Liechtenstein', 'country_arNationality' => 'ليختنشتيني'],
            ['code' => 'LT', 'country_enName' => 'Lithuania', 'country_arName' => 'لتوانيا', 'country_enNationality' => 'Lithuanian', 'country_arNationality' => 'لتوانيي'],
            ['code' => 'LU', 'country_enName' => 'Luxembourg', 'country_arName' => 'لوكسمبورغ', 'country_enNationality' => 'Luxembourger', 'country_arNationality' => 'لوكسمبورغي'],
            ['code' => 'LK', 'country_enName' => 'Sri Lanka', 'country_arName' => 'سريلانكا', 'country_enNationality' => 'Sri Lankian', 'country_arNationality' => 'سريلانكي'],
            ['code' => 'MO', 'country_enName' => 'Macau', 'country_arName' => 'ماكاو', 'country_enNationality' => 'Macanese', 'country_arNationality' => 'ماكاوي'],
            ['code' => 'MK', 'country_enName' => 'Macedonia', 'country_arName' => 'مقدونيا', 'country_enNationality' => 'Macedonian', 'country_arNationality' => 'مقدوني'],
            ['code' => 'MG', 'country_enName' => 'Madagascar', 'country_arName' => 'مدغشقر', 'country_enNationality' => 'Malagasy', 'country_arNationality' => 'مدغشقري'],
            ['code' => 'MW', 'country_enName' => 'Malawi', 'country_arName' => 'مالاوي', 'country_enNationality' => 'Malawian', 'country_arNationality' => 'مالاوي'],
            ['code' => 'MY', 'country_enName' => 'Malaysia', 'country_arName' => 'ماليزيا', 'country_enNationality' => 'Malaysian', 'country_arNationality' => 'ماليزي'],
            ['code' => 'MV', 'country_enName' => 'Maldives', 'country_arName' => 'المالديف', 'country_enNationality' => 'Maldivian', 'country_arNationality' => 'مالديفي'],
            ['code' => 'ML', 'country_enName' => 'Mali', 'country_arName' => 'مالي', 'country_enNationality' => 'Malian', 'country_arNationality' => 'مالي'],
            ['code' => 'MT', 'country_enName' => 'Malta', 'country_arName' => 'مالطا', 'country_enNationality' => 'Maltese', 'country_arNationality' => 'مالطي'],
            ['code' => 'MH', 'country_enName' => 'Marshall Islands', 'country_arName' => 'جزر مارشال', 'country_enNationality' => 'Marshallese', 'country_arNationality' => 'مارشالي'],
            ['code' => 'MQ', 'country_enName' => 'Martinique', 'country_arName' => 'مارتينيك', 'country_enNationality' => 'Martiniquais', 'country_arNationality' => 'مارتينيكي'],
            ['code' => 'MR', 'country_enName' => 'Mauritania', 'country_arName' => 'موريتانيا', 'country_enNationality' => 'Mauritanian', 'country_arNationality' => 'موريتانيي'],
            ['code' => 'MU', 'country_enName' => 'Mauritius', 'country_arName' => 'موريشيوس', 'country_enNationality' => 'Mauritian', 'country_arNationality' => 'موريشيوسي'],
            ['code' => 'YT', 'country_enName' => 'Mayotte', 'country_arName' => 'مايوت', 'country_enNationality' => 'Mahoran', 'country_arNationality' => 'مايوتي'],
            ['code' => 'MX', 'country_enName' => 'Mexico', 'country_arName' => 'المكسيك', 'country_enNationality' => 'Mexican', 'country_arNationality' => 'مكسيكي'],
            ['code' => 'FM', 'country_enName' => 'Micronesia', 'country_arName' => 'مايكرونيزيا', 'country_enNationality' => 'Micronesian', 'country_arNationality' => 'مايكرونيزيي'],
            ['code' => 'MD', 'country_enName' => 'Moldova', 'country_arName' => 'مولدافيا', 'country_enNationality' => 'Moldovan', 'country_arNationality' => 'مولديفي'],
            ['code' => 'MC', 'country_enName' => 'Monaco', 'country_arName' => 'موناكو', 'country_enNationality' => 'Monacan', 'country_arNationality' => 'مونيكي'],
            ['code' => 'MN', 'country_enName' => 'Mongolia', 'country_arName' => 'منغوليا', 'country_enNationality' => 'Mongolian', 'country_arNationality' => 'منغولي'],
            ['code' => 'ME', 'country_enName' => 'Montenegro', 'country_arName' => 'الجبل الأسود', 'country_enNationality' => 'Montenegrin', 'country_arNationality' => 'الجبل الأسود'],
            ['code' => 'MS', 'country_enName' => 'Montserrat', 'country_arName' => 'مونتسيرات', 'country_enNationality' => 'Montserratian', 'country_arNationality' => 'مونتسيراتي'],
            ['code' => 'MA', 'country_enName' => 'Morocco', 'country_arName' => 'المغرب', 'country_enNationality' => 'Moroccan', 'country_arNationality' => 'مغربي'],
            ['code' => 'MZ', 'country_enName' => 'Mozambique', 'country_arName' => 'موزمبيق', 'country_enNationality' => 'Mozambican', 'country_arNationality' => 'موزمبيقي'],
            ['code' => 'MM', 'country_enName' => 'Myanmar', 'country_arName' => 'ميانمار', 'country_enNationality' => 'Myanmarian', 'country_arNationality' => 'ميانماري'],
            ['code' => 'NA', 'country_enName' => 'Namibia', 'country_arName' => 'ناميبيا', 'country_enNationality' => 'Namibian', 'country_arNationality' => 'ناميبي'],
            ['code' => 'NR', 'country_enName' => 'Nauru', 'country_arName' => 'نورو', 'country_enNationality' => 'Nauruan', 'country_arNationality' => 'نوري'],            ['code' => 'Afghanistan', 'country_enName' => 'AF', 'country_arName' => 'AF', 'country_enNationality' => 'AF', 'country_arNationality' => 'AF'],
            ['code' => 'NP', 'country_enName' => 'Nepal', 'country_arName' => 'نيبال', 'country_enNationality' => 'Nepalese', 'country_arNationality' => 'نيبالي'],
            ['code' => 'NL', 'country_enName' => 'Netherlands', 'country_arName' => 'هولندا', 'country_enNationality' => 'Dutch', 'country_arNationality' => 'هولندي'],
            ['code' => 'AN', 'country_enName' => 'Netherlands Antilles', 'country_arName' => 'جزر الأنتيل الهولندي', 'country_enNationality' => 'Dutch Antilier', 'country_arNationality' => 'هولندي'],
            ['code' => 'NC', 'country_enName' => 'New Caledonia', 'country_arName' => 'كاليدونيا الجديدة', 'country_enNationality' => 'New Caledonian', 'country_arNationality' => 'كاليدوني'],
            ['code' => 'NZ', 'country_enName' => 'New Zealand', 'country_arName' => 'نيوزيلندا', 'country_enNationality' => 'New Zealander', 'country_arNationality' => 'نيوزيلندي'],
            ['code' => 'NI', 'country_enName' => 'Nicaragua', 'country_arName' => 'نيكاراجوا', 'country_enNationality' => 'Nicaraguan', 'country_arNationality' => 'نيكاراجوي'],
            ['code' => 'NE', 'country_enName' => 'Niger', 'country_arName' => 'النيجر', 'country_enNationality' => 'Nigerien', 'country_arNationality' => 'نيجيري'],
            ['code' => 'NG', 'country_enName' => 'Nigeria', 'country_arName' => 'نيجيريا', 'country_enNationality' => 'Nigerian', 'country_arNationality' => 'نيجيري'],
            ['code' => 'NU', 'country_enName' => 'Niue', 'country_arName' => 'ني', 'country_enNationality' => 'Niuean', 'country_arNationality' => 'ني'],
            ['code' => 'NF', 'country_enName' => 'Norfolk Island', 'country_arName' => 'جزيرة نورفولك', 'country_enNationality' => 'Norfolk Islander', 'country_arNationality' => 'نورفوليكي'],
            ['code' => 'MP', 'country_enName' => 'Northern Mariana Islands', 'country_arName' => 'جزر ماريانا الشمالية', 'country_enNationality' => 'Northern Marianan', 'country_arNationality' => 'ماريني'],
            ['code' => 'NO', 'country_enName' => 'Norway', 'country_arName' => 'النرويج', 'country_enNationality' => 'Norwegian', 'country_arNationality' => 'نرويجي'],
            ['code' => 'OM', 'country_enName' => 'Oman', 'country_arName' => 'عمان', 'country_enNationality' => 'Omani', 'country_arNationality' => 'عماني'],
            ['code' => 'PK', 'country_enName' => 'Pakistan', 'country_arName' => 'باكستان', 'country_enNationality' => 'Pakistani', 'country_arNationality' => 'باكستاني'],
            ['code' => 'PW', 'country_enName' => 'Palau', 'country_arName' => 'بالاو', 'country_enNationality' => 'Palauan', 'country_arNationality' => 'بالاوي'],
            ['code' => 'PS', 'country_enName' => 'Palestine', 'country_arName' => 'فلسطين', 'country_enNationality' => 'Palestinian', 'country_arNationality' => 'فلسطيني'],
            ['code' => 'PA', 'country_enName' => 'Panama', 'country_arName' => 'Panama', 'country_enNationality' => 'Panamanian', 'country_arNationality' => 'بنمي'],
            ['code' => 'PG', 'country_enName' => 'Papua New Guinea', 'country_arName' => 'بابوا غينيا الجديدة', 'country_enNationality' => 'Papua New Guinean', 'country_arNationality' => 'بابوي'],
            ['code' => 'PY', 'country_enName' => 'Paraguay', 'country_arName' => 'باراغواي', 'country_enNationality' => 'Paraguayan', 'country_arNationality' => 'بارغاوي'],
            ['code' => 'PE', 'country_enName' => 'Peru', 'country_arName' => 'بيرو', 'country_enNationality' => 'Peruvian', 'country_arNationality' => 'بيري'],
            ['code' => 'PH', 'country_enName' => 'Philippines', 'country_arName' => 'الفليبين', 'country_enNationality' => 'Filipino', 'country_arNationality' => 'فلبيني'],
            ['code' => 'PN', 'country_enName' => 'Pitcairn', 'country_arName' => 'بيتكيرن', 'country_enNationality' => 'Pitcairn Islander', 'country_arNationality' => 'بيتكيرني'],
            ['code' => 'PL', 'country_enName' => 'Poland', 'country_arName' => 'بولونيا', 'country_enNationality' => 'Polish', 'country_arNationality' => 'بوليني'],
            ['code' => 'PT', 'country_enName' => 'Portugal', 'country_arName' => 'البرتغال', 'country_enNationality' => 'Portuguese', 'country_arNationality' => 'برتغالي'],
            ['code' => 'PR', 'country_enName' => 'Puerto Rico', 'country_arName' => 'بورتو ريكو', 'country_enNationality' => 'Puerto Rican', 'country_arNationality' => 'بورتي'],
            ['code' => 'QA', 'country_enName' => 'Qatar', 'country_arName' => 'قطر', 'country_enNationality' => 'Qatari', 'country_arNationality' => 'قطري'],
            ['code' => 'RE', 'country_enName' => 'Reunion Island', 'country_arName' => 'ريونيون', 'country_enNationality' => 'Reunionese', 'country_arNationality' => 'ريونيوني'],
            ['code' => 'RO', 'country_enName' => 'Romania', 'country_arName' => 'رومانيا', 'country_enNationality' => 'Romanian', 'country_arNationality' => 'روماني'],
            ['code' => 'RU', 'country_enName' => 'Russian', 'country_arName' => 'روسيا', 'country_enNationality' => 'Russian', 'country_arNationality' => 'روسي'],
            ['code' => 'RW', 'country_enName' => 'Rwanda', 'country_arName' => 'رواندا', 'country_enNationality' => 'Rwandan', 'country_arNationality' => 'رواندا'],
            ['code' => 'KN', 'country_enName' => 'Saint Kitts and Nevis', 'country_arName' => 'سانت كيتس ونيفس', 'country_enNationality' => 'Kittitian/Nevisian', 'country_arNationality' => 'سانت كيتس ونيفس'],
            ['code' => 'MF', 'country_enName' => 'Saint Martin (French part)', 'country_arName' => 'ساينت مارتن فرنسي', 'country_enNationality' => 'St. Martian(French)', 'country_arNationality' => 'ساينت مارتني فرنسي'],
            ['code' => 'SX', 'country_enName' => 'Sint Maarten (Dutch part)', 'country_arName' => 'ساينت مارتن هولندي', 'country_enNationality' => 'St. Martian(Dutch)', 'country_arNationality' => 'ساينت مارتني هولندي'],
            ['code' => 'LC', 'country_enName' => 'Saint Pierre and Miquelon', 'country_arName' => 'سان بيير وميكلون', 'country_enNationality' => 'St. Pierre and Miquelon', 'country_arNationality' => 'سان بيير وميكلوني'],
            ['code' => 'VC', 'country_enName' => 'Saint Vincent and the Grenadines', 'country_arName' => 'سانت فنسنت وجزر غرينادين', 'country_enNationality' => 'Saint Vincent and the Grenadines', 'country_arNationality' => 'سانت فنسنت وجزر غرينادين'],
            ['code' => 'WS', 'country_enName' => 'Samoa', 'country_arName' => 'ساموا', 'country_enNationality' => 'Samoan', 'country_arNationality' => 'ساموي'],
            ['code' => 'SM', 'country_enName' => 'San Marino', 'country_arName' => 'سان مارينو', 'country_enNationality' => 'Sammarinese', 'country_arNationality' => 'ماريني'],
            ['code' => 'ST', 'country_enName' => 'Sao Tome and Principe', 'country_arName' => 'ساو تومي وبرينسيبي', 'country_enNationality' => 'Sao Tomean', 'country_arNationality' => 'ساو تومي وبرينسيبي'],
            ['code' => 'SA', 'country_enName' => 'Saudi Arabia', 'country_arName' => 'المملكة العربية السعودية', 'country_enNationality' => 'Saudi Arabian', 'country_arNationality' => 'سعودي'],
            ['code' => 'SN', 'country_enName' => 'Senegal', 'country_arName' => 'السنغال', 'country_enNationality' => 'Senegalese', 'country_arNationality' => 'سنغالي'],
            ['code' => 'RS', 'country_enName' => 'Serbia', 'country_arName' => 'صربيا', 'country_enNationality' => 'Serbian', 'country_arNationality' => 'صربي'],
            ['code' => 'SC', 'country_enName' => 'Seychelles', 'country_arName' => 'سيشيل', 'country_enNationality' => 'Seychellois', 'country_arNationality' => 'سيشيلي'],
            ['code' => 'SL', 'country_enName' => 'Sierra Leone', 'country_arName' => 'سيراليون', 'country_enNationality' => 'Sierra Leonean', 'country_arNationality' => 'سيراليوني'],
            ['code' => 'SG', 'country_enName' => 'Singapore', 'country_arName' => 'سنغافورة', 'country_enNationality' => 'Singaporean', 'country_arNationality' => 'سنغافوري'],
            ['code' => 'SK', 'country_enName' => 'Slovakia', 'country_arName' => 'سلوفاكيا', 'country_enNationality' => 'Slovak', 'country_arNationality' => 'سولفاكي'],
            ['code' => 'SI', 'country_enName' => 'Slovenia', 'country_arName' => 'سلوفينيا', 'country_enNationality' => 'Slovenian', 'country_arNationality' => 'سولفيني'],
            ['code' => 'SB', 'country_enName' => 'Solomon Islands', 'country_arName' => 'جزر سليمان', 'country_enNationality' => 'Solomon Island', 'country_arNationality' => 'جزر سليمان'],
            ['code' => 'SO', 'country_enName' => 'Somalia', 'country_arName' => 'الصومال', 'country_enNationality' => 'Somali', 'country_arNationality' => 'صومالي'],
            ['code' => 'ZA', 'country_enName' => 'South Africa', 'country_arName' => 'جنوب أفريقيا', 'country_enNationality' => 'South African', 'country_arNationality' => 'أفريقي'],
            ['code' => 'SS', 'country_enName' => 'South Sudan', 'country_arName' => 'السودان الجنوبي', 'country_enNationality' => 'South Sudanese', 'country_arNationality' => 'سوادني جنوبي'],
            ['code' => 'ES', 'country_enName' => 'Spain', 'country_arName' => 'إسبانيا', 'country_enNationality' => 'Spanish', 'country_arNationality' => 'إسباني'],
            ['code' => 'SH', 'country_enName' => 'Saint Helena', 'country_arName' => 'سانت هيلانة', 'country_enNationality' => 'St. Helenian', 'country_arNationality' => 'هيلاني'],
            ['code' => 'SD', 'country_enName' => 'Sudan', 'country_arName' => 'السودان', 'country_enNationality' => 'Sudanese', 'country_arNationality' => 'سوداني'],
            ['code' => 'SR', 'country_enName' => 'Suriname', 'country_arName' => 'سورينام', 'country_enNationality' => 'Surinamese', 'country_arNationality' => 'سورينامي'],
            ['code' => 'SZ', 'country_enName' => 'Swaziland', 'country_arName' => 'سوازيلند', 'country_enNationality' => 'Swazi', 'country_arNationality' => 'سوازيلندي'],
            ['code' => 'SE', 'country_enName' => 'Sweden', 'country_arName' => 'السويد', 'country_enNationality' => 'Swedish', 'country_arNationality' => 'سويدي'],
            ['code' => 'CH', 'country_enName' => 'Switzerland', 'country_arName' => 'سويسرا', 'country_enNationality' => 'Swiss', 'country_arNationality' => 'سويسري'],
            ['code' => 'SY', 'country_enName' => 'Syria', 'country_arName' => 'سوريا', 'country_enNationality' => 'Syrian', 'country_arNationality' => 'سوري'],
            ['code' => 'TW', 'country_enName' => 'Taiwan', 'country_arName' => 'تايوان', 'country_enNationality' => 'Taiwanese', 'country_arNationality' => 'تايواني'],
            ['code' => 'TJ', 'country_enName' => 'Tajikistan', 'country_arName' => 'طاجيكستان', 'country_enNationality' => 'Tajikistani', 'country_arNationality' => 'طاجيكستاني'],
            ['code' => 'TZ', 'country_enName' => 'Tanzania', 'country_arName' => 'تنزانيا', 'country_enNationality' => 'Tanzanian', 'country_arNationality' => 'تنزانيي'],
            ['code' => 'TH', 'country_enName' => 'Thailand', 'country_arName' => 'تايلندا', 'country_enNationality' => 'Thai', 'country_arNationality' => 'تايلندي'],
            ['code' => 'TL', 'country_enName' => 'Timor-Leste', 'country_arName' => 'تيمور الشرقية', 'country_enNationality' => 'Timor-Lestian', 'country_arNationality' => 'تيموري'],
            ['code' => 'TG', 'country_enName' => 'Togo', 'country_arName' => 'توغو', 'country_enNationality' => 'Togolese', 'country_arNationality' => 'توغي'],
            ['code' => 'TK', 'country_enName' => 'Tokelau', 'country_arName' => 'توكيلاو', 'country_enNationality' => 'Tokelaian', 'country_arNationality' => 'توكيلاوي'],
            ['code' => 'TO', 'country_enName' => 'Tonga', 'country_arName' => 'تونغا', 'country_enNationality' => 'Tongan', 'country_arNationality' => 'تونغي'],
            ['code' => 'TN', 'country_enName' => 'Tunisia', 'country_arName' => 'تونس', 'country_enNationality' => 'Tunisian', 'country_arNationality' => 'تونسي'],
            ['code' => 'TR', 'country_enName' => 'Turkey', 'country_arName' => 'تركيا', 'country_enNationality' => 'Turkish', 'country_arNationality' => 'تركي'],
            ['code' => 'TM', 'country_enName' => 'Turkmenistan', 'country_arName' => 'تركمانستان', 'country_enNationality' => 'Turkmen', 'country_arNationality' => 'تركمانستاني'],
            ['code' => 'TV', 'country_enName' => 'Tuvalu', 'country_arName' => 'توفالو', 'country_enNationality' => 'Tuvaluan', 'country_arNationality' => 'توفالي'],
            ['code' => 'UG', 'country_enName' => 'Uganda', 'country_arName' => 'أوغندا', 'country_enNationality' => 'Ugandan', 'country_arNationality' => 'أوغندي'],
            ['code' => 'UA', 'country_enName' => 'Ukraine', 'country_arName' => 'Ukraine', 'country_enNationality' => 'Ukrainian', 'country_arNationality' => 'أوكراني'],
            ['code' => 'AE', 'country_enName' => 'United Arab Emirates', 'country_arName' => 'الإمارات العربية المتحدة', 'country_enNationality' => 'Emirati', 'country_arNationality' => 'إماراتي'],
            ['code' => 'GB', 'country_enName' => 'United Kingdom', 'country_arName' => 'المملكة المتحدة', 'country_enNationality' => 'British', 'country_arNationality' => 'بريطاني'],
            ['code' => 'US', 'country_enName' => 'United States', 'country_arName' => 'الولايات المتحدة', 'country_enNationality' => 'American', 'country_arNationality' => 'أمريكي'],
            ['code' => 'UY', 'country_enName' => 'Uruguay', 'country_arName' => 'أورغواي', 'country_enNationality' => 'Uruguayan', 'country_arNationality' => 'أورغواي'],
            ['code' => 'UZ', 'country_enName' => 'Uzbekistan', 'country_arName' => 'أوزباكستان', 'country_enNationality' => 'Uzbek', 'country_arNationality' => 'أوزباكستاني'],
            ['code' => 'VU', 'country_enName' => 'Vanuatu', 'country_arName' => 'فانواتو', 'country_enNationality' => 'Vanuatuan', 'country_arNationality' => 'فانواتي'],
            ['code' => 'VE', 'country_enName' => 'Venezuela', 'country_arName' => 'فنزويلا', 'country_enNationality' => 'Venezuelan', 'country_arNationality' => 'فنزويلي'],
            ['code' => 'VN', 'country_enName' => 'Vietnam', 'country_arName' => 'فيتنام', 'country_enNationality' => 'Vietnamese', 'country_arNationality' => 'فيتنامي'],
            ['code' => 'VA', 'country_enName' => 'Vatican City', 'country_arName' => 'فاتيكان', 'country_enNationality' => 'Vatican', 'country_arNationality' => 'فاتيكاني'],
            ['code' => 'EH', 'country_enName' => 'Western Sahara', 'country_arName' => 'الصحراء الغربية', 'country_enNationality' => 'Sahrawian', 'country_arNationality' => 'صحراوي'],
            ['code' => 'YE', 'country_enName' => 'Yemen', 'country_arName' => 'اليمن', 'country_enNationality' => 'Yemeni', 'country_arNationality' => 'يمني'],
            ['code' => 'ZM', 'country_enName' => 'Zambia', 'country_arName' => 'زامبيا', 'country_enNationality' => 'Zambian', 'country_arNationality' => 'زامبياني'],
            ['code' => 'ZW', 'country_enName' => 'Zimbabwe', 'country_arName' => 'زمبابوي', 'country_enNationality' => 'Zimbabwean', 'country_arNationality' => 'زمبابوي'],
        ];

        DB::table('countries')->insert($countries);*/

        DB::table('countries')->delete();
        $countries = array(
            array('id' => 1,'code' => 'AF' ,'name' => "Afghanistan",'phone_code' => 93),
            array('id' => 2,'code' => 'AL' ,'name' => "Albania",'phone_code' => 355),
            array('id' => 3,'code' => 'DZ' ,'name' => "Algeria",'phone_code' => 213),
            array('id' => 4,'code' => 'AS' ,'name' => "American Samoa",'phone_code' => 1684),
            array('id' => 5,'code' => 'AD' ,'name' => "Andorra",'phone_code' => 376),
            array('id' => 6,'code' => 'AO' ,'name' => "Angola",'phone_code' => 244),
            array('id' => 7,'code' => 'AI' ,'name' => "Anguilla",'phone_code' => 1264),
            array('id' => 8,'code' => 'AQ' ,'name' => "Antarctica",'phone_code' => 0),
            array('id' => 9,'code' => 'AG' ,'name' => "Antigua And Barbuda",'phone_code' => 1268),
            array('id' => 10,'code' => 'AR','name' => "Argentina",'phone_code' => 54),
            array('id' => 11,'code' => 'AM','name' => "Armenia",'phone_code' => 374),
            array('id' => 12,'code' => 'AW','name' => "Aruba",'phone_code' => 297),
            array('id' => 13,'code' => 'AU','name' => "Australia",'phone_code' => 61),
            array('id' => 14,'code' => 'AT','name' => "Austria",'phone_code' => 43),
            array('id' => 15,'code' => 'AZ','name' => "Azerbaijan",'phone_code' => 994),
            array('id' => 16,'code' => 'BS','name' => "Bahamas The",'phone_code' => 1242),
            array('id' => 17,'code' => 'BH','name' => "Bahrain",'phone_code' => 973),
            array('id' => 18,'code' => 'BD','name' => "Bangladesh",'phone_code' => 880),
            array('id' => 19,'code' => 'BB','name' => "Barbados",'phone_code' => 1246),
            array('id' => 20,'code' => 'BY','name' => "Belarus",'phone_code' => 375),
            array('id' => 21,'code' => 'BE','name' => "Belgium",'phone_code' => 32),
            array('id' => 22,'code' => 'BZ','name' => "Belize",'phone_code' => 501),
            array('id' => 23,'code' => 'BJ','name' => "Benin",'phone_code' => 229),
            array('id' => 24,'code' => 'BM','name' => "Bermuda",'phone_code' => 1441),
            array('id' => 25,'code' => 'BT','name' => "Bhutan",'phone_code' => 975),
            array('id' => 26,'code' => 'BO','name' => "Bolivia",'phone_code' => 591),
            array('id' => 27,'code' => 'BA','name' => "Bosnia and Herzegovina",'phone_code' => 387),
            array('id' => 28,'code' => 'BW','name' => "Botswana",'phone_code' => 267),
            array('id' => 29,'code' => 'BV','name' => "Bouvet Island",'phone_code' => 0),
            array('id' => 30,'code' => 'BR','name' => "Brazil",'phone_code' => 55),
            array('id' => 31,'code' => 'IO','name' => "British Indian Ocean Territory",'phone_code' => 246),
            array('id' => 32,'code' => 'BN','name' => "Brunei",'phone_code' => 673),
            array('id' => 33,'code' => 'BG','name' => "Bulgaria",'phone_code' => 359),
            array('id' => 34,'code' => 'BF','name' => "Burkina Faso",'phone_code' => 226),
            array('id' => 35,'code' => 'BI','name' => "Burundi",'phone_code' => 257),
            array('id' => 36,'code' => 'KH','name' => "Cambodia",'phone_code' => 855),
            array('id' => 37,'code' => 'CM','name' => "Cameroon",'phone_code' => 237),
            array('id' => 38,'code' => 'CA','name' => "Canada",'phone_code' => 1),
            array('id' => 39,'code' => 'CV','name' => "Cape Verde",'phone_code' => 238),
            array('id' => 40,'code' => 'KY','name' => "Cayman Islands",'phone_code' => 1345),
            array('id' => 41,'code' => 'CF','name' => "Central African Republic",'phone_code' => 236),
            array('id' => 42,'code' => 'TD','name' => "Chad",'phone_code' => 235),
            array('id' => 43,'code' => 'CL','name' => "Chile",'phone_code' => 56),
            array('id' => 44,'code' => 'CN','name' => "China",'phone_code' => 86),
            array('id' => 45,'code' => 'CX','name' => "Christmas Island",'phone_code' => 61),
            array('id' => 46,'code' => 'CC','name' => "Cocos (Keeling) Islands",'phone_code' => 672),
            array('id' => 47,'code' => 'CO','name' => "Colombia",'phone_code' => 57),
            array('id' => 48,'code' => 'KM','name' => "Comoros",'phone_code' => 269),
            array('id' => 49,'code' => 'CG','name' => "Congo",'phone_code' => 242),
            array('id' => 50,'code' => 'CD','name' => "Congo The Democratic Republic Of The",'phone_code' => 242),
            array('id' => 51,'code' => 'CK','name' => "Cook Islands",'phone_code' => 682),
            array('id' => 52,'code' => 'CR','name' => "Costa Rica",'phone_code' => 506),
            array('id' => 53,'code' => 'CI','name' => "Cote D Ivoire (Ivory Coast)",'phone_code' => 225),
            array('id' => 54,'code' => 'HR','name' => "Croatia (Hrvatska)",'phone_code' => 385),
            array('id' => 55,'code' => 'CU','name' => "Cuba",'phone_code' => 53),
            array('id' => 56,'code' => 'CY','name' => "Cyprus",'phone_code' => 357),
            array('id' => 57,'code' => 'CZ','name' => "Czech Republic",'phone_code' => 420),
            array('id' => 58,'code' => 'DK','name' => "Denmark",'phone_code' => 45),
            array('id' => 59,'code' => 'DJ','name' => "Djibouti",'phone_code' => 253),
            array('id' => 60,'code' => 'DM','name' => "Dominica",'phone_code' => 1767),
            array('id' => 61,'code' => 'DO','name' => "Dominican Republic",'phone_code' => 1809),
            array('id' => 62,'code' => 'TP','name' => "East Timor",'phone_code' => 670),
            array('id' => 63,'code' => 'EC','name' => "Ecuador",'phone_code' => 593),
            array('id' => 64,'code' => 'EG','name' => "Egypt",'phone_code' => 20),
            array('id' => 65,'code' => 'SV','name' => "El Salvador",'phone_code' => 503),
            array('id' => 66,'code' => 'GQ','name' => "Equatorial Guinea",'phone_code' => 240),
            array('id' => 67,'code' => 'ER','name' => "Eritrea",'phone_code' => 291),
            array('id' => 68,'code' => 'EE','name' => "Estonia",'phone_code' => 372),
            array('id' => 69,'code' => 'ET','name' => "Ethiopia",'phone_code' => 251),
            array('id' => 70,'code' => 'XA','name' => "External Territories of Australia",'phone_code' => 61),
            array('id' => 71,'code' => 'FK','name' => "Falkland Islands",'phone_code' => 500),
            array('id' => 72,'code' => 'FO','name' => "Faroe Islands",'phone_code' => 298),
            array('id' => 73,'code' => 'FJ','name' => "Fiji Islands",'phone_code' => 679),
            array('id' => 74,'code' => 'FI','name' => "Finland",'phone_code' => 358),
            array('id' => 75,'code' => 'FR','name' => "France",'phone_code' => 33),
            array('id' => 76,'code' => 'GF','name' => "French Guiana",'phone_code' => 594),
            array('id' => 77,'code' => 'PF','name' => "French Polynesia",'phone_code' => 689),
            array('id' => 78,'code' => 'TF','name' => "French Southern Territories",'phone_code' => 0),
            array('id' => 79,'code' => 'GA','name' => "Gabon",'phone_code' => 241),
            array('id' => 80,'code' => 'GM','name' => "Gambia The",'phone_code' => 220),
            array('id' => 81,'code' => 'GE','name' => "Georgia",'phone_code' => 995),
            array('id' => 82,'code' => 'DE','name' => "Germany",'phone_code' => 49),
            array('id' => 83,'code' => 'GH','name' => "Ghana",'phone_code' => 233),
            array('id' => 84,'code' => 'GI','name' => "Gibraltar",'phone_code' => 350),
            array('id' => 85,'code' => 'GR','name' => "Greece",'phone_code' => 30),
            array('id' => 86,'code' => 'GL','name' => "Greenland",'phone_code' => 299),
            array('id' => 87,'code' => 'GD','name' => "Grenada",'phone_code' => 1473),
            array('id' => 88,'code' => 'GP','name' => "Guadeloupe",'phone_code' => 590),
            array('id' => 89,'code' => 'GU','name' => "Guam",'phone_code' => 1671),
            array('id' => 90,'code' => 'GT','name' => "Guatemala",'phone_code' => 502),
            array('id' => 91,'code' => 'XU','name' => "Guernsey and Alderney",'phone_code' => 44),
            array('id' => 92,'code' => 'GN','name' => "Guinea",'phone_code' => 224),
            array('id' => 93,'code' => 'GW','name' => "Guinea-Bissau",'phone_code' => 245),
            array('id' => 94,'code' => 'GY','name' => "Guyana",'phone_code' => 592),
            array('id' => 95,'code' => 'HT','name' => "Haiti",'phone_code' => 509),
            array('id' => 96,'code' => 'HM','name' => "Heard and McDonald Islands",'phone_code' => 0),
            array('id' => 97,'code' => 'HN','name' => "Honduras",'phone_code' => 504),
            array('id' => 98,'code' => 'HK','name' => "Hong Kong S.A.R.",'phone_code' => 852),
            array('id' => 99,'code' => 'HU','name' => "Hungary",'phone_code' => 36),
            array('id' => 100,'code' => 'IS','name' => "Iceland",'phone_code' => 354),
            array('id' => 101,'code' => 'IN','name' => "India",'phone_code' => 91),
            array('id' => 102,'code' => 'ID','name' => "Indonesia",'phone_code' => 62),
            array('id' => 103,'code' => 'IR','name' => "Iran",'phone_code' => 98),
            array('id' => 104,'code' => 'IQ','name' => "Iraq",'phone_code' => 964),
            array('id' => 105,'code' => 'IE','name' => "Ireland",'phone_code' => 353),
            array('id' => 106,'code' => 'IL','name' => "Israel",'phone_code' => 972),
            array('id' => 107,'code' => 'IT','name' => "Italy",'phone_code' => 39),
            array('id' => 108,'code' => 'JM','name' => "Jamaica",'phone_code' => 1876),
            array('id' => 109,'code' => 'JP','name' => "Japan",'phone_code' => 81),
            array('id' => 110,'code' => 'XJ','name' => "Jersey",'phone_code' => 44),
            array('id' => 111,'code' => 'JO','name' => "Jordan",'phone_code' => 962),
            array('id' => 112,'code' => 'KZ','name' => "Kazakhstan",'phone_code' => 7),
            array('id' => 113,'code' => 'KE','name' => "Kenya",'phone_code' => 254),
            array('id' => 114,'code' => 'KI','name' => "Kiribati",'phone_code' => 686),
            array('id' => 115,'code' => 'KP','name' => "Korea North",'phone_code' => 850),
            array('id' => 116,'code' => 'KR','name' => "Korea South",'phone_code' => 82),
            array('id' => 117,'code' => 'KW','name' => "Kuwait",'phone_code' => 965),
            array('id' => 118,'code' => 'KG','name' => "Kyrgyzstan",'phone_code' => 996),
            array('id' => 119,'code' => 'LA','name' => "Laos",'phone_code' => 856),
            array('id' => 120,'code' => 'LV','name' => "Latvia",'phone_code' => 371),
            array('id' => 121,'code' => 'LB','name' => "Lebanon",'phone_code' => 961),
            array('id' => 122,'code' => 'LS','name' => "Lesotho",'phone_code' => 266),
            array('id' => 123,'code' => 'LR','name' => "Liberia",'phone_code' => 231),
            array('id' => 124,'code' => 'LY','name' => "Libya",'phone_code' => 218),
            array('id' => 125,'code' => 'LI','name' => "Liechtenstein",'phone_code' => 423),
            array('id' => 126,'code' => 'LT','name' => "Lithuania",'phone_code' => 370),
            array('id' => 127,'code' => 'LU','name' => "Luxembourg",'phone_code' => 352),
            array('id' => 128,'code' => 'MO','name' => "Macau S.A.R.",'phone_code' => 853),
            array('id' => 129,'code' => 'MK','name' => "Macedonia",'phone_code' => 389),
            array('id' => 130,'code' => 'MG','name' => "Madagascar",'phone_code' => 261),
            array('id' => 131,'code' => 'MW','name' => "Malawi",'phone_code' => 265),
            array('id' => 132,'code' => 'MY','name' => "Malaysia",'phone_code' => 60),
            array('id' => 133,'code' => 'MV','name' => "Maldives",'phone_code' => 960),
            array('id' => 134,'code' => 'ML','name' => "Mali",'phone_code' => 223),
            array('id' => 135,'code' => 'MT','name' => "Malta",'phone_code' => 356),
            array('id' => 136,'code' => 'XM','name' => "Man (Isle of)",'phone_code' => 44),
            array('id' => 137,'code' => 'MH','name' => "Marshall Islands",'phone_code' => 692),
            array('id' => 138,'code' => 'MQ','name' => "Martinique",'phone_code' => 596),
            array('id' => 139,'code' => 'MR','name' => "Mauritania",'phone_code' => 222),
            array('id' => 140,'code' => 'MU','name' => "Mauritius",'phone_code' => 230),
            array('id' => 141,'code' => 'YT','name' => "Mayotte",'phone_code' => 269),
            array('id' => 142,'code' => 'MX','name' => "Mexico",'phone_code' => 52),
            array('id' => 143,'code' => 'FM','name' => "Micronesia",'phone_code' => 691),
            array('id' => 144,'code' => 'MD','name' => "Moldova",'phone_code' => 373),
            array('id' => 145,'code' => 'MC','name' => "Monaco",'phone_code' => 377),
            array('id' => 146,'code' => 'MN','name' => "Mongolia",'phone_code' => 976),
            array('id' => 147,'code' => 'MS','name' => "Montserrat",'phone_code' => 1664),
            array('id' => 148,'code' => 'MA','name' => "Morocco",'phone_code' => 212),
            array('id' => 149,'code' => 'MZ','name' => "Mozambique",'phone_code' => 258),
            array('id' => 150,'code' => 'MM','name' => "Myanmar",'phone_code' => 95),
            array('id' => 151,'code' => 'NA','name' => "Namibia",'phone_code' => 264),
            array('id' => 152,'code' => 'NR','name' => "Nauru",'phone_code' => 674),
            array('id' => 153,'code' => 'NP','name' => "Nepal",'phone_code' => 977),
            array('id' => 154,'code' => 'AN','name' => "Netherlands Antilles",'phone_code' => 599),
            array('id' => 155,'code' => 'NL','name' => "Netherlands The",'phone_code' => 31),
            array('id' => 156,'code' => 'NC','name' => "New Caledonia",'phone_code' => 687),
            array('id' => 157,'code' => 'NZ','name' => "New Zealand",'phone_code' => 64),
            array('id' => 158,'code' => 'NI','name' => "Nicaragua",'phone_code' => 505),
            array('id' => 159,'code' => 'NE','name' => "Niger",'phone_code' => 227),
            array('id' => 160,'code' => 'NG','name' => "Nigeria",'phone_code' => 234),
            array('id' => 161,'code' => 'NU','name' => "Niue",'phone_code' => 683),
            array('id' => 162,'code' => 'NF','name' => "Norfolk Island",'phone_code' => 672),
            array('id' => 163,'code' => 'MP','name' => "Northern Mariana Islands",'phone_code' => 1670),
            array('id' => 164,'code' => 'NO','name' => "Norway",'phone_code' => 47),
            array('id' => 165,'code' => 'OM','name' => "Oman",'phone_code' => 968),
            array('id' => 166,'code' => 'PK','name' => "Pakistan",'phone_code' => 92),
            array('id' => 167,'code' => 'PW','name' => "Palau",'phone_code' => 680),
            array('id' => 168,'code' => 'PS','name' => "Palestinian Territory Occupied",'phone_code' => 970),
            array('id' => 169,'code' => 'PA','name' => "Panama",'phone_code' => 507),
            array('id' => 170,'code' => 'PG','name' => "Papua new Guinea",'phone_code' => 675),
            array('id' => 171,'code' => 'PY','name' => "Paraguay",'phone_code' => 595),
            array('id' => 172,'code' => 'PE','name' => "Peru",'phone_code' => 51),
            array('id' => 173,'code' => 'PH','name' => "Philippines",'phone_code' => 63),
            array('id' => 174,'code' => 'PN','name' => "Pitcairn Island",'phone_code' => 0),
            array('id' => 175,'code' => 'PL','name' => "Poland",'phone_code' => 48),
            array('id' => 176,'code' => 'PT','name' => "Portugal",'phone_code' => 351),
            array('id' => 177,'code' => 'PR','name' => "Puerto Rico",'phone_code' => 1787),
            array('id' => 178,'code' => 'QA','name' => "Qatar",'phone_code' => 974),
            array('id' => 179,'code' => 'RE','name' => "Reunion",'phone_code' => 262),
            array('id' => 180,'code' => 'RO','name' => "Romania",'phone_code' => 40),
            array('id' => 181,'code' => 'RU','name' => "Russia",'phone_code' => 70),
            array('id' => 182,'code' => 'RW','name' => "Rwanda",'phone_code' => 250),
            array('id' => 183,'code' => 'SH','name' => "Saint Helena",'phone_code' => 290),
            array('id' => 184,'code' => 'KN','name' => "Saint Kitts And Nevis",'phone_code' => 1869),
            array('id' => 185,'code' => 'LC','name' => "Saint Lucia",'phone_code' => 1758),
            array('id' => 186,'code' => 'PM','name' => "Saint Pierre and Miquelon",'phone_code' => 508),
            array('id' => 187,'code' => 'VC','name' => "Saint Vincent And The Grenadines",'phone_code' => 1784),
            array('id' => 188,'code' => 'WS','name' => "Samoa",'phone_code' => 684),
            array('id' => 189,'code' => 'SM','name' => "San Marino",'phone_code' => 378),
            array('id' => 190,'code' => 'ST','name' => "Sao Tome and Principe",'phone_code' => 239),
            array('id' => 191,'code' => 'SA','name' => "Saudi Arabia",'phone_code' => 966),
            array('id' => 192,'code' => 'SN','name' => "Senegal",'phone_code' => 221),
            array('id' => 193,'code' => 'RS','name' => "Serbia",'phone_code' => 381),
            array('id' => 194,'code' => 'SC','name' => "Seychelles",'phone_code' => 248),
            array('id' => 195,'code' => 'SL','name' => "Sierra Leone",'phone_code' => 232),
            array('id' => 196,'code' => 'SG','name' => "Singapore",'phone_code' => 65),
            array('id' => 197,'code' => 'SK','name' => "Slovakia",'phone_code' => 421),
            array('id' => 198,'code' => 'SI','name' => "Slovenia",'phone_code' => 386),
            array('id' => 199,'code' => 'XG','name' => "Smaller Territories of the UK",'phone_code' => 44),
            array('id' => 200,'code' => 'SB','name' => "Solomon Islands",'phone_code' => 677),
            array('id' => 201,'code' => 'SO','name' => "Somalia",'phone_code' => 252),
            array('id' => 202,'code' => 'ZA','name' => "South Africa",'phone_code' => 27),
            array('id' => 203,'code' => 'GS','name' => "South Georgia",'phone_code' => 0),
            array('id' => 204,'code' => 'SS','name' => "South Sudan",'phone_code' => 211),
            array('id' => 205,'code' => 'ES','name' => "Spain",'phone_code' => 34),
            array('id' => 206,'code' => 'LK','name' => "Sri Lanka",'phone_code' => 94),
            array('id' => 207,'code' => 'SD','name' => "Sudan",'phone_code' => 249),
            array('id' => 208,'code' => 'SR','name' => "Suriname",'phone_code' => 597),
            array('id' => 209,'code' => 'SJ','name' => "Svalbard And Jan Mayen Islands",'phone_code' => 47),
            array('id' => 210,'code' => 'SZ','name' => "Swaziland",'phone_code' => 268),
            array('id' => 211,'code' => 'SE','name' => "Sweden",'phone_code' => 46),
            array('id' => 212,'code' => 'CH','name' => "Switzerland",'phone_code' => 41),
            array('id' => 213,'code' => 'SY','name' => "Syria",'phone_code' => 963),
            array('id' => 214,'code' => 'TW','name' => "Taiwan",'phone_code' => 886),
            array('id' => 215,'code' => 'TJ','name' => "Tajikistan",'phone_code' => 992),
            array('id' => 216,'code' => 'TZ','name' => "Tanzania",'phone_code' => 255),
            array('id' => 217,'code' => 'TH','name' => "Thailand",'phone_code' => 66),
            array('id' => 218,'code' => 'TG','name' => "Togo",'phone_code' => 228),
            array('id' => 219,'code' => 'TK','name' => "Tokelau",'phone_code' => 690),
            array('id' => 220,'code' => 'TO','name' => "Tonga",'phone_code' => 676),
            array('id' => 221,'code' => 'TT','name' => "Trinidad And Tobago",'phone_code' => 1868),
            array('id' => 222,'code' => 'TN','name' => "Tunisia",'phone_code' => 216),
            array('id' => 223,'code' => 'TR','name' => "Turkey",'phone_code' => 90),
            array('id' => 224,'code' => 'TM','name' => "Turkmenistan",'phone_code' => 7370),
            array('id' => 225,'code' => 'TC','name' => "Turks And Caicos Islands",'phone_code' => 1649),
            array('id' => 226,'code' => 'TV','name' => "Tuvalu",'phone_code' => 688),
            array('id' => 227,'code' => 'UG','name' => "Uganda",'phone_code' => 256),
            array('id' => 228,'code' => 'UA','name' => "Ukraine",'phone_code' => 380),
            array('id' => 229,'code' => 'AE','name' => "United Arab Emirates",'phone_code' => 971),
            array('id' => 230,'code' => 'GB','name' => "United Kingdom",'phone_code' => 44),
            array('id' => 231,'code' => 'US','name' => "United States",'phone_code' => 1),
            array('id' => 232,'code' => 'UM','name' => "United States Minor Outlying Islands",'phone_code' => 1),
            array('id' => 233,'code' => 'UY','name' => "Uruguay",'phone_code' => 598),
            array('id' => 234,'code' => 'UZ','name' => "Uzbekistan",'phone_code' => 998),
            array('id' => 235,'code' => 'VU','name' => "Vanuatu",'phone_code' => 678),
            array('id' => 236,'code' => 'VA','name' => "Vatican City State (Holy See)",'phone_code' => 39),
            array('id' => 237,'code' => 'VE','name' => "Venezuela",'phone_code' => 58),
            array('id' => 238,'code' => 'VN','name' => "Vietnam",'phone_code' => 84),
            array('id' => 239,'code' => 'VG','name' => "Virgin Islands (British)",'phone_code' => 1284),
            array('id' => 240,'code' => 'VI','name' => "Virgin Islands (US)",'phone_code' => 1340),
            array('id' => 241,'code' => 'WF','name' => "Wallis And Futuna Islands",'phone_code' => 681),
            array('id' => 242,'code' => 'EH','name' => "Western Sahara",'phone_code' => 212),
            array('id' => 243,'code' => 'YE','name' => "Yemen",'phone_code' => 967),
            array('id' => 244,'code' => 'YU','name' => "Yugoslavia",'phone_code' => 38),
            array('id' => 245,'code' => 'ZM','name' => "Zambia",'phone_code' => 260),
            array('id' => 246,'code' => 'ZW','name' => "Zimbabwe",'phone_code' => 263),
        );
        DB::table('countries')->insert($countries);
    }
}
